version: "3.8"

services:
  excala-api:
    build:
      context: .
    image: excala-api
    container_name: excalaapp-api
    volumes:
      # Comentar caso esteja em AWS/PROD
      - ${EXCALA_DEPLOY_PATH}:/excala/api
    ports:
      - "5005:5005"
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7.40-debian
    container_name: excala_db
    environment:
      MYSQL_DATABASE: $DS_DATABASE
      MYSQL_USER: $DS_USERNAME
      MYSQL_PASSWORD: $DS_PASSWORD
      MYSQL_ROOT_PASSWORD: $DS_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql $$DS_DATABASE -uroot -p$$MYSQL_PASSWORD -e 'SELECT 1;'"]
      interval: 10s
      timeout: 10s
      retries: 5
