spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://db:3306/excalaapp
    username: excalaapp
    password: excalaapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: excalapoll
      connection-test-query: select 1;
      maximum-pool-size: 50
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true
jwt:
  secret: ${JWT_SECRET}